[ui.window.box]
width = 150
min_width = 150
max_width = 150
height = 180
min_height = 180
max_height = 180

# List constraints are critical - without these, the window shrinks when empty
[ui.window.box.scroll.list]
width = 150
min_width = 150
max_width = 150
height = 180
min_height = 180
max_height = 180

[ui.window.box.scroll.list.item.icon]
pixel_size = 40
