[ui.window.box]
width = 200
min_width = 200
max_width = 200
height = 300
min_height = 300
max_height = 300

# List constraints are critical - without these, the window shrinks when empty
[ui.window.box.scroll.list]
height = 200
min_height = 200
max_height = 200

[ui.window.box.scroll.list.item.icon]
pixel_size = 40
