[ui.window.box]
width = 660
min_width = 660
max_width = 660
height = 300
min_height = 300
max_height = 300

# List constraints are critical - without these, the window shrinks when empty
[ui.window.box.scroll.list]
height = 230
min_height = 230
max_height = 230

[ui.window.box.scroll.list.item.icon]
pixel_size = 40
