app_launch_prefix = "uwsm app -- "
theme = "lomarchy"
theme_location = ["~/.config/walker/mythemes/"]

[search]
placeholder = "Search..."

[builtins.runner]
switcher_only = true
hidden = true

[builtins.hyprland_keybinds]
switcher_only = true
hidden = true

[builtins.applications]
launch_prefix = "uwsm app -- "
placeholder = "Search..."
prioritize_new = false
context_aware = false
show_sub_when_single = false
history = false
icon = ""
hidden = true

[builtins.applications.actions]
enabled = false
hide_category = true

[builtins.translation]
delay = 1000
weight = 5
name = "translation"
icon = "accessories-dictionary"
placeholder = "Translation"
switcher_only = false
provider = "googlefree"
hidden = false

[builtins.commands]
switcher_only = true
hidden = true

[builtins.custom_commands]
switcher_only = true
hidden = true

[builtins.windows]
switcher_only = true
hidden = true

[builtins.finder]
switcher_only = true
hidden = true

[builtins.ssh]
hidden = true

[builtins.websearch]
switcher_only = true
hidden = true

[builtins.bookmarks]
hidden = true
