app_launch_prefix = "uwsm app -- "
theme = "lomarchy"
theme_location = ["~/.config/walker/mythemes/"]

[search]
placeholder = " Search..."

[builtins.runner]
switcher_only = true
hidden = true

[builtins.hyprland_keybinds]
switcher_only = true
hidden = true

[builtins.translation]
delay = 1000
weight = 5
name = "translation"
icon = "accessories-dictionary"
placeholder = "Translation"
switcher_only = false
provider = "googlefree"
hidden = false

[builtins.commands]
switcher_only = true
hidden = true

[builtins.custom_commands]
switcher_only = true
hidden = true

[builtins.windows]
switcher_only = true
hidden = true

[builtins.finder]
switcher_only = true
hidden = true
